version: "3"
services:
  springapp:
    image: 686255940829.dkr.ecr.ap-south-1.amazonaws.com/spring-boot-mongo-docker:VERSION
    environment:
      - MONGO-BD-HOSTNAME:MONGO
      - MONGO-DB-USERNAME:devdb
      - MONGO-DB-PASSWORD:devdb@123
    ports:
    - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappbridge
    deploy:  # This will be considered only in docker swarm.
      placement:
        constraints: 
         - node.labels.name==workerone
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    
  mongo:
    image: mongo
    volumes:
    - mongovolu:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb 
      - MONGO_INITDB_ROOT_PASSWORD=devdb1234 
    networks:
    - springappbridge
    
volumes:
  mongovolu: 
    external: true

networks:
  springappbridge:
    external: true
   