version: "3"
services:
  springapp:
    image: 686255940829.dkr.ecr.ap-south-1.amazonaws.com/spring-boot-mongo-docker:VERSION
    ports:
    - 8080:8080
    networks:
    - springappbridge
    environment:
      - MONGO-BD-HOSTNAME:MONGO
      - MONGO-DB-USERNAME:devdb
      - MONGO-DB-PASSWORD:devdb@123

  mongo:
    image: mongo
    volumes:
    - mongovolu:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb 
      - MONGO_INITDB_ROOT_PASSWORD=devdb1234 
    networks:
    - springappbridge

volumes:
  mongovolu: 
networks:
  springappbridge:
   